=== nikita-nikiforov/epam/lesson0212/XMLParser/target/classes/xml/candies.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="candies"
           xmlns="candies"
           elementFormDefault="qualified">

    <xs:element name="candies">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="candy" type="candyType"
                            maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="candyType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="energy" type="xs:integer"/>
            <xs:element name="type" type="xs:string"/>
            <xs:element name="ingredients">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element name="ingredient" type="xs:string"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
            <xs:element name="value">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="proteins" type="xs:integer"/>
                        <xs:element name="fat" type="xs:integer"/>
                        <xs:element name="carbohydrates" type="xs:integer"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="manufacturer" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>



</xs:schema>

=== nikita-nikiforov/epam/lesson0212/XMLParser/src/main/resources/xml/candies.xml
<?xml version="1.0" encoding="UTF-8"?>

<candies xmlns="candies"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="candies.xsd">
	<candy>
		<name>Ромашка</name>
		<energy>150</energy>
		<type>Шоколадна</type>
		<ingredients>
			<ingredient>Шоколад</ingredient>
			<ingredient>Ромашка</ingredient>
		</ingredients>
		<value>
			<proteins>113</proteins>
			<fat>46</fat>
			<carbohydrates>91</carbohydrates>
		</value>
		<manufacturer>Рошен</manufacturer>
	</candy>

	<candy>
		<name>Ментолова</name>
		<energy>715</energy>
		<type>Смоктальна</type>
		<ingredients>
			<ingredient>Ментол</ingredient>
			<ingredient>М'ята</ingredient>
		</ingredients>
		<value>
			<proteins>361</proteins>
			<fat>71</fat>
			<carbohydrates>57</carbohydrates>
		</value>
		<manufacturer>Рошен</manufacturer>
	</candy>
</candies>
